### ISSUE TITLE
Roll ( Bowling - Java )

### ISSUE THREAD

**Issue by 3xpl0itk1t** [csivitu/ArcadeGames#30]
**Describe the bug**
The game still rolls the ball even if you type a number rather than roll

**To Reproduce**
1. Go to './javgames/basketball'
2. Run 'basketball.java'
3. Enter a number instead of roll

**Expected behavior**
It should not work on any command rather than roll.

**Comment by RupaakSrinivas** [comment]
Please assign this to me

**Comment by anirudh233** [comment]
please assign this to me

**Comment by GeekArjun29** [comment]
assign this to me please

**Comment by 3xpl0itk1t** [comment]
@anirudh233  @GeekArjun29  you can work on it even if its not assigned we just need your pr's.

**Comment by 3xpl0itk1t** [comment]
This issue has been resolved.
