### ISSUE TITLE
Second Move ( TicTacToe - JS )

### ISSUE THREAD

**Issue by 3xpl0itk1t** [csivitu/ArcadeGames#33]
**Describe the bug**
It stops working on the 2nd move

**To Reproduce**
1. Go to '.jsgames/tictactoe'
2. Run 'index.html'
3. Try playing

**Expected behavior**
It should keep working for the whole match

**Comment by semi-infiknight** [comment]
please assign this issue to me

**Comment by raji2004** [comment]
i would love to be assigned this issue

**Comment by 3xpl0itk1t** [comment]
this issue has been resolved.

**Comment by raji2004** [comment]
> this issue has been resolved.

its saying not accepted on my profile
