### ISSUE TITLE
Speed Increase ( SpaceInvaders - Python )

### ISSUE THREAD

**Issue by 3xpl0itk1t** [csivitu/ArcadeGames#34]
**Describe the bug**
There is no speed increase warning for the aliens

**To Reproduce**
1. Go to '.pygames/spaceinvaders'
2. Run 'main.py'
4. Play for a bit
5. See error

**Expected behavior**
It should give a warning for speed increase of the aliens before it does.

**Comment by GeekArjun29** [comment]
Assign this to me

**Comment by TanishqSrivastava** [comment]
Can you assign this to me?

**Comment by karanbihani** [comment]
assign this to me

**Comment by RupaakSrinivas** [comment]
Assign this to me

**Comment by 3xpl0itk1t** [comment]
You have to contribute on your own we can't keep on assigning issues as there are a lot of issues.

**Comment by 3xpl0itk1t** [comment]
This issue has been closed.
