### ISSUE TITLE
Multiplayer ( TicTacToe - JS )

### ISSUE THREAD

**Issue by 3xpl0itk1t** [csivitu/ArcadeGames#42]
**Is your feature request related to a problem? Please describe.**
No 2 player mode

**Describe the solution you'd like**
Add a new feature for a multiplayer mode so that 2 people can play.

**Comment by RahatAhmed171** [comment]
Hi, I've previously made tic tac toe game with two players. Would love to contribute to this issue!

**Comment by 3xpl0itk1t** [comment]
> Hi, I've previously made tic tac toe game with two players. Would love to contribute to this issue!

I have assigned you to this issue free feel to contribute

**Comment by YatishSikka** [comment]
Hi, I'm interested in this issue and have some experience in this area, would love to contribute to this issue.
