### ISSUE TITLE
Create A Readme ( RockPaperScissor - Python )

### ISSUE THREAD

**Issue by 3xpl0itk1t** [csivitu/ArcadeGames#44]
**Location of the Document**
You have to create a Readme for RockPaperScissor

**What needs to be added**
Create and Add details about the game.

**Comment by RupaakSrinivas** [comment]
give me access for this issue

**Comment by VibhorAgrawal2003** [comment]
Assign this to me.

**Comment by 3xpl0itk1t** [comment]
This issue has been resolved
