### ISSUE TITLE
Create A Readme ( RussianRoulette - JS )

### ISSUE THREAD

**Issue by 3xpl0itk1t** [csivitu/ArcadeGames#46]
**Location of the Document**
You have to create a Readme for RussianRoulette

**What needs to be added**
Create and Add details about the game.

**Comment by chiragchandnani10** [comment]
Can you please assign it to me.? Thanks!

**Comment by Suryanshu-09** [comment]
Assign this to me.

**Comment by RupaakSrinivas** [comment]
@3xpl0itk1t , Please close this issue, the README is done
