### ISSUE TITLE
Create A Readme ( Bowling - Java )

### ISSUE THREAD

**Issue by 3xpl0itk1t** [csivitu/ArcadeGames#50]
**Location of the Document**
You have to create a Readme for Bowling

**What needs to be added**
Create and Add details about the game.

**Comment by Ishita-Jinturkar** [comment]
assign this to me

**Comment by Suryanshu-09** [comment]
#Assign this to me.

**Comment by Suryanshu-09** [comment]
Assign this to me.

**Comment by RupaakSrinivas** [comment]
@3xpl0itk1t , the readme for this game is already updated, why is the issue still open??
