### ISSUE TITLE
Create A Readme ( Snake - Python )

### ISSUE THREAD

**Issue by 3xpl0itk1t** [csivitu/ArcadeGames#51]
**Location of the Document**
You have to create a Readme for Snake

**What needs to be added**
Create and Add details about the game.

**Comment by RupaakSrinivas** [comment]
assign this to me

**Comment by pushpavalliPI** [comment]
assign this to me

**Comment by RupaakSrinivas** [comment]
@SubstantialCattle5 , Why is this issue still open??
