### ISSUE TITLE
Flappy Game - Python

### ISSUE THREAD

**Issue by 3xpl0itk1t** [csivitu/ArcadeGames#78]
**What needs to be added**
The screenshots are not loading
<img width="704" alt="Screenshot 2022-10-01 at 6 13 59 PM" src="https://user-images.githubusercontent.com/64297193/193410211-0d47a9dd-cbc0-4efa-8028-672921821fc3.png">

**Solution** 
Fix the README.md such that it loads the screenshots.

**Comment by SauravKalita22** [comment]
Is this issue open? If it is, can you please assign this issue to me? I am a beginner and really would like to fix this issue.

**Comment by VibhorAgrawal2003** [comment]
Assign this to me.

**Comment by VibhorAgrawal2003** [comment]
Assign this to me.
