### ISSUE TITLE
[Feat] Add Pacman

### ISSUE THREAD

**Issue by SubstantialCattle5** [csivitu/ArcadeGames#86]
**Is your feature request related to a problem? Please describe.**
I wanna play pacman. 

**Describe the solution you'd like**
play pacman

**Additional context**
Try using pygame for it.

**Comment by RupaakSrinivas** [comment]
@SubstantialCattle5 , can we use Turtle for this project?

**Comment by SubstantialCattle5** [comment]
> @SubstantialCattle5  @3xpl0itk1t , can we use Turtle for this project?

Use whatever you want just make it fun!!!!
