### ISSUE TITLE
[Feat] : Adding timelimit for each point (snake - python)

### ISSUE THREAD

**Issue by RupaakSrinivas** [csivitu/ArcadeGames#89]
**Is your feature request related to a problem? Please describe.**
The time limit which is existing is for the whole game, 10 secs is the time limit, which severely restricts the player from going to higher levels

**Describe the solution you'd like**
Instead of the time limit for the whole game, create a time limit for each point

**Comment by RupaakSrinivas** [comment]
@SubstantialCattle5 @3xpl0itk1t , please accept and label the issue

**Comment by 3xpl0itk1t** [comment]
@RupaakSrinivas you can work on your issue.
