### ISSUE TITLE
[FEAT] Asteroids 

### ISSUE THREAD

**Issue by SubstantialCattle5** [csivitu/ArcadeGames#91]
**Is your feature request related to a problem? Please describe.**
 
I'm always frustrated when I can't play asteroids 

**Describe the solution you'd like**
I want to play Asteroids 

**Additional context**
Try using pygame.

**Comment by AkshayArjun** [comment]
pls assign it to me.

**Comment by RupaakSrinivas** [comment]
Please assign this issue to me
