### ISSUE TITLE
Proposal to add project contributors details in Readme file

### ISSUE THREAD

**Issue by aritroo** [csivitu/ArcadeGames#99]
Hello @3xpl0itk1t 
What about adding the project contributors profile in the footer of readme ?
I want to work on it please assign it to me.
Hope you will like it.

**Comment by 3xpl0itk1t** [comment]
Sure

**Comment by sanjaybaskaran01** [comment]
Please look into [all-contributors](https://github.com/all-contributors/app) bot

**Comment by aritroo** [comment]
> Please look into [all-contributors](https://github.com/all-contributors/app) bot

Sure 😊
